name: master/deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn generate --fail-on-error
        env:
          GA_ID: ${{ secrets.GA_ID }}
      - name: Archive master Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./client/dist
          if-no-files-found: error
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./client/dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client
