name: CI

on:
  pull_request:
    branches:
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: production
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn generate
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
