name: master/pre-merge

on:
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          yarn install
          yarn generate --fail-on-error
        working-directory: client
      - name: Start server
        run: yarn start &
        working-directory: client
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/spec.js
          working-directory: uitest
