name: master/pre-merge

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn generate --fail-on-error
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/spec.js
          build: yarn build
          start: yarn start
